### ISSUE TITLE
User Login not working

### ISSUE THREAD

**Issue by Bala-Logesh** [Bala-Logesh/Se23-Slash-61#10]
Incorrect comparison in the main.py file 

# Function to get a user from the database
def get_user_by_email(db: Session, email: str):
    return db.query(UserCreate).filter(UserCreate.username == email).first()

Not username must be email
    return db.query(UserCreate).filter(UserCreate.email == email).first()

**Comment by SahanaYelchuri** [comment]
Issue fixed(see commit bde5e3c33a376242352f1a892858bceb38f15f40)
