### ISSUE TITLE
Declaration warning running pytest - models.py

### ISSUE THREAD

**Issue by Bala-Logesh** [Bala-Logesh/Se23-Slash-61#4]
In models.py:17: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    Base = declarative_base()

**Comment by SahanaYelchuri** [comment]
Not a breaking change. No modifications.
