### ISSUE TITLE
Target scrapper not working on Mac OS

### ISSUE THREAD

**Issue by Bala-Logesh** [Bala-Logesh/Se23-Slash-61#5]
I am getting this following error: 

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

**Comment by RatishkumarS** [comment]
Issue fixed (see commit-06f8de3aaae8c2c29371e5545280472f3dc03b99)
